version: '3'
services:
  web:
    image: nginx:1.19
    container_name: webserver
    ports:
    - "80:80"
    volumes:
    - ./web/default.conf:/etc/nginx/conf.d/default.conf
    - ${ROOT}:/var/www/html
    depends_on:
      - webapp
  webapp:
    build: ./webapp
    working_dir: /var/www/html
    container_name: laravel
    volumes:
      - ${ROOT}:/var/www/html
      - ${LOG}:/log
      - ./webapp/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - database
  node:
    image: node:13
    container_name: node
    tty: true
    working_dir: /var/www/html
    ports:
    - "8002:80"
    volumes:
    - ${ROOT}:/var/www/html
  database:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=Hoangdo@123
      - MYSQL_ROOT_PASSWORD=Hoangdo@123
      - TZ=Asia/Tokyo
    ports:
        - "33062:3306"
  smtp:
    image: mailhog/mailhog
    container_name: mail
    ports:
    - "8025:8025"
    - "25:25"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25
    user: root
    working_dir: /mailhog
volumes:
  dbdata: